[package]
name = "pacrust"
version = "0.1.0"
authors = ["POLLIEN Baptiste <baptiste.pollien@isae-supaero.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.3"
rand = "0.8.3"